### ISSUE TITLE
Separate declarations from side-effects

### ISSUE THREAD

**Issue by szepeviktor** [Underpin-WP/underpin#7]
1. move the main class to lib/Underpin.php
1. move underpin() to lib/helpers.php
1. autoload wordpress-autoloader.php and lib/helpers.php with Composer
1. Provide an example of loading Underpin - see below
1. remove autoloading from abstracts\Underpin

```php
require_once __DIR_ . '/vendor/autoload.php';

add_action( 'plugins_loaded', '\\Underpin\\underpin' );
```

**Comment by szepeviktor** [comment]
`wordpress-autoloader.php`

```php
<?php
/**
 * Autoloader for WordPress.
 *
 * @package Underpin
 * @link https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions
 * @link https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md#class-example
 */

declare( strict_types = 1 );

namespace Underpin;

use function spl_autoload_register;

spl_autoload_register(
	/**
	 * Closure of the autoloader.
	 *
	 * @param class-string $class_name The fully-qualified class name.
	 * @return void
	 */
	static function ( $class_name ) {
		$project_namespace = __NAMESPACE__ . '\\';
		$length            = strlen( $project_namespace );

		// Class is not in our namespace.
		if ( 0 !== strncmp( $project_namespace, $class_name, $length ) ) {
			return;
		}

		// E.g. Model\Item
		$relative_class_name = substr( $class_name, $length );
		// E.g. model/Item.php
		$name_parts = explode( '\\', $relative_class_name );
		$last_part  = array_pop( $name_parts );

		$file = sprintf(
			'%1$s/lib%2$s/%3$s.php',
			__DIR__,
			array() === $name_parts ? '' : '/' . strtolower( str_replace( '_', '-', implode( '/', $name_parts ) ) ),
			$last_part
		);

		if ( ! is_file( $file ) ) {
			return;
		}

		require $file;
	}
);
```

Original: https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wp-install/wordpress-autoloader.php

**Comment by szepeviktor** [comment]
We currently have a mix of PSR-4 class file names and WPCS directory names.

- be bold and use PSR-4 everywhere not just in file names (see Rector)
- or be old-bold and use updated WPCS everywhere :) https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/

**Comment by szepeviktor** [comment]
Going further: `underpin()->` may be replaced with a DI container

**Comment by szepeviktor** [comment]
After everything is clean and tidy: `phpstan.neon.dist`

```neon
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
#    level: max
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - lib/
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters(_ref_array)? invoked with [34567] parameters, 2 required\.$#'
```

>  [ERROR] Found 74 errors

Will keep you entertained for 2 hours.

**Comment by alexstandiford** [comment]
> or be old-bold and use updated WPCS everywhere :) https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/

Nope. This plugin is unapologetic-ally intended to avoid that. To me, if you want to use WPCS, use WordPress.

I appreciate the information in this, would it be possible to have a PR submitted? That would make it _way_ easier to understand the differences, and test.

**Comment by szepeviktor** [comment]
Done.
